config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :purchasers
  resource :session
  resources :passwords, param: :token
  get "purchases/index"
  root "imports#new"

  resources :imports
  resources :purchases
  resources :users

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
  end

  def create
    file = params[:file]

    if file.nil?
      redirect_to new_import_path, alert: "Nenhum arquivo selecionado."
      return
    end

    if file.content_type != "application/octet-stream"
      redirect_to new_import_path, alert: "Somente arquivos .tab e .csv são aceitos."
      return
    end

    begin
      result = TabFileImporter.call(file, current_user.id)
      redirect_to purchases_path, notice: "Importação concluída. Receita total: R$ #{'%.2f' % result}"
    rescue => e
      logger.error "Erro ao importar TAB: #{e.class} - #{e.message}"
      redirect_to new_import_path, alert: "Erro na leitura do arquivo. Certifique-se de que está salvo em UTF-8 e no formato correto."
    end
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/create.html.erb
<h1>Imports#create</h1>
<p>Find me in app/views/imports/create.html.erb</p>

app/views/imports/new.html.erb
<div class="d-flex" style="min-height: 100vh;">
  <div class="container container-menu py-4">
    <h2>Importar Arquivo</h2>

    <%= form_with url: imports_path, local: true, multipart: true do |form| %>

      <%= form.label :file, "Selecione um arquivo para importar" %><br><br><br>
      <%= form.file_field :file %>
      <br><br>
    <div class="text-center mt-3">
      <%= form.submit "Importar", class: "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>