config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :purchasers
  resource :session
  resources :passwords, param: :token
  get "purchases/index"
  root "imports#new"

  resources :imports
  resources :purchases
  resources :users

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :merchant

  validates :description, presence: true
  validates :price,  presence: true
  validates :merchant_id, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = current_user.items
  end

  def show
  end

  def new
    @item = Item.new
    @merchants = Merchant.all
  end

  def edit
    @item = Item.find(params[:id])
    @merchants = Merchant.all
  end

  def create
    @item = current_user.items.build(item_params)
    @merchants = Merchant.all

    if @item.save
      redirect_to @item, notice: 'Item criado com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy!
    redirect_to items_path, status: :see_other, notice: "Item foi excluído com sucesso."
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html {redirect_to @item, notice: "Item atualizado com sucesso!." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:description, :price, :merchant_id)
    end
end

app/views/items/edit.html.erb
<% content_for :title, "Editar Cadastro de Item" %>

<div class="container container-menu">
  <h1>Editar Item</h1>

  <% if @item.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@item.errors.count, "erro") %> impediram o salvamento:</h2>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @item, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :description, "Descrição", class: "form-label" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :price, "Preço", class: "form-label" %>
      <%= form.number_field :price, step: 0.01, class: "form-control" %>
    </div>
<div class="text-center">
    <%= form.submit "Atualizar", class: "btn btn-primary" %>
</div>
  <% end %>

  <div class="mt-3 d-flex gap-2">
    <%= link_to "Visualizar Item", @item, class: "btn btn-outline-info" %>
  </div>
</div>

app/views/items/index.html.erb
<% content_for :title, "Lista de Itens Cadastrados" %>

<div class="table-responsive container-compras">
  <p class="text-success"><%= notice %></p>

  <h1 class="text-center">Itens Cadastrados</h1>

  <div id="items" class="row">
    <% @items.each do |item| %>
      <% if item.user_id == current_user.id %>
        <div class="col-md-4 mb-4">
          <div class="card shadow-sm h-100">
            <div class="card-body">
              <h5 class="card-title"><%= item.description %></h5>
              <p class="card-text"><strong>Preço:</strong> <%= number_to_currency(item.price, unit: "R$", separator: ",", delimiter: ".") %></p>
              <p class="card-text text-muted">ID do Comerciante: <%= item.merchant_id %></p>
              <%= link_to "Visualizar Item", item, class: "btn btn-primary btn-sm" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>
</div>

app/views/items/new.html.erb
<% content_for :title, "Cadastro de Novo Item" %>

<div class="container container-menu">
  <h1>Cadastro Novo Item</h1>

  <% if @item.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@item.errors.count, "erro") %> impediram o salvamento:</h2>
      <ul class="error-list">
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @item, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :price, class: "form-label" %>
      <%= form.number_field :price, class: "form-control", step: 0.01 %>
    </div>

    <div class="mb-3">
    <%= form.label :merchant_id, "Comerciante", class: "form-label" %>
    <%= form.collection_select :merchant_id, @merchants, :id, :name, { prompt: "Selecione um comerciante" }, { class: "form-select" } %>
    </div>
<div class="text-center">
    <%= form.submit "Salvar", class: "btn btn-success" %>
</div>
  <% end %>

  <br>

  <div>
  </div>
</div>

app/views/items/show.html.erb
<% content_for :title, "Detalhes do Item" %>

<div class="container container-menu">
  <p class="text-success"><%= notice %></p>

  <h1>Detalhes do Item</h1>

  <div class="card shadow-sm my-4">
    <div class="card-body">
      <h5 class="card-title"><strong>Descrição:</strong> <%= @item.description %></h5>
      <p class="card-text"><strong>Preço:</strong> <%= number_to_currency(@item.price, unit: "R$", separator: ",", delimiter: ".") %></p>
      <p class="card-text text-muted"><strong>ID do Comerciante:</strong> <%= @item.merchant_id %></p>
    </div>
  </div>

  <div class="d-flex gap-2">
    <%= link_to "Editar Item", edit_item_path(@item), class: "btn btn-outline-primary" %>
  </div>
</div>