config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :purchasers
  resource :session
  resources :passwords, param: :token
  get "purchases/index"
  root "imports#new"

  resources :imports
  resources :purchases
  resources :users

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Upload Arquivo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", media: "all" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

 <% sidebar_excluded = !current_user || controller.controller_name.in?(%w[sessions passwords]) || (controller.controller_name == 'users' && controller.action_name.in?(%w[new create])) %>

<body class="<%= sidebar_excluded ? '' : 'd-flex' %>" style="min-height: 100vh;">
  <div class="<%= sidebar_excluded ? '' : 'd-flex' %> w-100">
    
    <% unless sidebar_excluded %>
      <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 250px;">
        <h2 class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
          <span class="fs-4">Lista de Compras</span>
        </h2>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li><%= link_to "Importador de Arquivo", new_import_path, class: "nav-link text-white" %></li>
          <br>
          <li><%= link_to "Página Inicial", purchases_index_path, class:"nav-link text-white" %></li>
          <li><%= link_to "Cadastro de Itens", new_item_path, class: "nav-link text-white" %></li>
          <li><%= link_to "Cadastro de Comprador", new_purchaser_path, class: "nav-link text-white" %></li>
          <li><%= link_to "Lista de itens", items_path, class: "nav-link text-white" %></li>
          <li><%= link_to "Lista de compradores", purchasers_path, class:"nav-link text-white" %></li>
        </ul>
        <% if authenticated? %>
          <%= button_to "Sair", session_path, method: :delete, class: "btn btn-danger mt-auto" %>
        <% end %>
      </div>
    <% end %>

    <main class="flex-grow-1 p-4 <%= sidebar_excluded ? 'container' : '' %>">
      <% flash.each do |type, message| %>
  <div class="alert alert-<%= type == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
      <%= yield %>
    </main>

  </div>
</body>